#P41 3-8
places = ['yunnan','guangdong','beijing','hunan','chengdu']
print(places)
places.sort()
print(places)
print(places)
places.sort(reverse=True)
print(places)
print(places)
print('\n')
places.sort(reverse=True)
print(places)
places.sort(reverse=True)
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)
print('\n')
#P42 3-9
num = len(places)
print(num)
#P42 3-10
cars = ['bwm','audi','toyota','subaru']
cars.sort()
print(cars)
cars.sort(reverse=True)
print(cars)
print('\n')
cars.sort()
print(cars)
cars = ['bwm','audi','toyota','subaru']
print(sorted(cars))
print(cars)
cars.reverse()
print(cars)
num = len(cars)
print(num)
